company_priorities:
  high_priority:
    - "caci"
    - "booz allen"
    - "parsons"
    - "aerospace corporation"
    - "hii"
    - "saic"
    - "leidos"
    - "lockheed martin"
    - "northrop grumman"
    - "odyssey systems"
    - "linquest"
    - "arcfield"
    - "mantech"
    - "peraton"
    - "amentum"
    - "bae systems"
    - "mtsi"
    - "bluehalo"
    - "slingshot aerospace"
    - "anduril"
    - "true anomaly"
    - "anthropic"
    - "openai"
    - "airtable"
    - "govini"

  medium_priority:
    - "kbr"
    - "rocket lab"
    - "redwire"
    - "sierra space"
    - "retool"
    - "notion"
    - "ironclad"
    - "monday.com"
    - "asana"
    - "pinecone"
    - "databricks"

  exploratory:
    - "team rubicon"
    - "direct relief"
    - "world central kitchen"
    - "international rescue committee"
    - "givedirectly"
